NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 3;
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 1;
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 2;
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 10;
NDefines.NCountry.EVENT_PROCESS_OFFSET = 30
NDefines_Graphics.NGraphics.MAPICON_GROUP_PASSES = 10
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999
NDefines.NGame.GARRISON_LOG_MAX_MONTHS = 0
NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 7
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 7

------balance changes------
NDefines.NCountry.STARTING_FUEL_RATIO = 0.5					-- starting fuel ratio compared to max fuel for countries
NDefines.NCountry.BASE_FUEL_GAIN_PER_OIL = 1.75						-- base amount of fuel gained hourly per excess oil
NDefines.NCountry.BASE_FUEL_GAIN = 0.0			-- base amount of fuel gained hourly, independent of excess oil
NDefines.NCountry.BASE_FUEL_CAPACITY = 100000					-- base amount of fuel capacity






------AI IMPROVEMNT------
NDefines.NAI.MAX_VOLUNTEER_ARMY_FRACTION = 1.00
NDefines.NAI.DIPLOMACY_ACCEPT_VOLUNTEERS_BASE = 150
NDefines.NAI.DIPLOMACY_SEND_MAX_FACTION = 0.0
NDefines.NAI.DIPLO_PREFER_OTHER_FACTION = -400
NDefines.NAI.PEACE_BID_FOLD_TURNS_AGAINST_OTHER_AI = 20
NDefines.NAI.DAYS_FUEL_REMAINING_TO_ENTER_FUEL_SAVING_MODE = 10
NDefines.NAI.MAX_FUEL_CONSUMPTION_RATIO_FOR_NAVY_TRAINING = 0.60
NDefines.NAI.DIPLOMACY_LEND_LEASE_MONTHS_TO_CANCEL = 1
NDefines.NAI.MINIMUM_FUEL_DAYS_TO_ASK_LEND_LEASE = 120
NDefines.NAI.MINIMUM_FUEL_DAYS_TO_ACCEPT_LEND_LEASE = 60
NDefines.NAI.BUILDING_TARGETS_BUILDING_PRIORITIES = {
		'air_base',
		'infrastructure',
		'nuclear_reactor',
		'nuclear_reactor_heavy_water',
		'synthetic_refinery',
		'dockyard',
		'industrial_complex',
	}
NDefines.NAI.CONSTRUCTION_PRIO_SUPPLY_BUILDING = 3.50
NDefines.NAI.CONSTRUCTION_PRIO_RAILWAY = 20.0
NDefines.NAI.CONSTRUCTION_PRIO_FACTOR_OWNED_CORE = 5.0
NDefines.NAI.CONSTRUCTION_PRIO_FACTOR_OWNED_NONCORE = 3.0
NDefines.NAI.RESEARCH_DAYS_BETWEEN_WEIGHT_UPDATE = 1
NDefines.NAI.RESEARCH_AHEAD_BONUS_FACTOR = 10.0
NDefines.NAI.RESEARCH_AHEAD_OF_TIME_FACTOR = 1.5
NDefines.NAI.RESEARCH_BONUS_FACTOR = 2
NDefines.NAI.MAX_AHEAD_RESEARCH_PENALTY = 7
NDefines.NAI.RESEARCH_YEARS_BEHIND_FACTOR = 0.20
NDefines.NAI.DEPLOY_MIN_TRAINING_SURRENDER_FACTOR = 0.5
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_SURRENDER_FACTOR = 0.90 
NDefines.NAI.DEPLOY_MIN_TRAINING_PEACE_FACTOR = 1
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_PEACE_FACTOR = 0.70
NDefines.NAI.DEPLOY_MIN_TRAINING_WAR_FACTOR = 1
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_WAR_FACTOR = 0.85
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_CAP_DEPLOY_FACTOR = 0.85
NDefines.NAI.UPGRADE_DIVISION_RELUCTANCE = 3
NDefines.NAI.UPGRADE_PERCENTAGE_OF_FORCES = 0.10
NDefines.NAI.DAYS_BETWEEN_CHECK_BEST_TEMPLATE = 7
NDefines.NAI.DAYS_BETWEEN_CHECK_BEST_EQUIPMENT = 7
NDefines.NAI.STOP_TRAINING_FULLY_TRAINED_FACTOR = 0.99
NDefines.NAI.UPGRADES_DEFICIT_LIMIT_DAYS = 60
NDefines.NAI.LOW_PRIO_TEMPLATE_BONUS_FOR_GARRISONS = 300000
NDefines.NAI.LOW_PRIO_TEMPLATE_PENALTY_FOR_FRONTS = -2000
NDefines.NAI.DESIRE_USE_XP_TO_UPDATE_LAND_TEMPLATE = 25.0
NDefines.NAI.VARIANT_CREATION_XP_RESERVE_LAND = 10
NDefines.NAI.DESIRE_USE_XP_TO_UNLOCK_LAND_DOCTRINE = 10
NDefines.NAI.DESIRE_USE_XP_TO_UNLOCK_NAVAL_DOCTRINE = 0.5
NDefines.NAI.DESIRE_USE_XP_TO_UNLOCK_AIR_DOCTRINE = 0.5
NDefines.NAI.DESIRE_USE_XP_TO_UNLOCK_ARMY_SPIRIT = 0.4
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_LAND_EQUIPMENT = 50.0
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_NAVAL_EQUIPMENT = 1.0
NDefines.NAI.DESIRE_USE_XP_TO_UPGRADE_AIR_EQUIPMENT = 15.0
NDefines.NAI.DEFAULT_LEGACY_VARIANT_CREATION_XP_CUTOFF_LAND = 20
NDefines.NAI.DEFAULT_MODULE_VARIANT_CREATION_XP_CUTOFF_LAND = 10
NDefines.NAI.DEFAULT_MODULE_VARIANT_CREATION_XP_CUTOFF_NAVY = 50
NDefines.NAI.DEFAULT_MODULE_VARIANT_CREATION_XP_CUTOFF_AIR = 25
NDefines.NAI.DEFAULT_LEGACY_VARIANT_CREATION_XP_CUTOFF_AIR = 20
NDefines.NAI.VARIANT_CREATION_XP_RESERVE_NAVY = 30
NDefines.NAI.VARIANT_CREATION_XP_RESERVE_AIR  = 30
NDefines.NAI.PRODUCTION_EQUIPMENT_SURPLUS_FACTOR = 0.6
NDefines.NAI.PRODUCTION_LINE_SWITCH_SURPLUS_NEEDED_MODIFIER = 0.4
NDefines.NAI.RAILWAY_GUN_PRODUCTION_BASE_DIVISIONS_RATIO_PERCENT = 5
NDefines.NAI.RAILWAY_GUN_PRODUCTION_MIN_DIVISONS = 100
NDefines.NAI.RAILWAY_GUN_PRODUCTION_MIN_FACTORIES = 50
NDefines.NAI.INDUSTRIAL_ORG_TRAIT_UNLOCK_RANDOMNESS = 1.0
NDefines.NAI.INDUSTRIAL_ORG_RESEARCH_ASSIGN_RANDOMNESS = 1.0
NDefines.NAI.INDUSTRIAL_ORG_PRODUCTION_ASSIGN_RANDOMNESS = 1.0
NDefines.NAI.TRADEABLE_FACTORIES_FRACTION = 1.0
NDefines.NAI.MINIMUM_GOOD_TRADE_RATIO_PER_CIV = 0.025 
NDefines.NAI.MIN_DELIVERED_TRADE_FRACTION = 0.70
NDefines.NAI.REFIT_SHIP_RELUCTANCE = 5000
NDefines.NAI.REFIT_SHIP_PERCENTAGE_OF_FORCES = 0.33
NDefines.NAI.MIN_NAVAL_MISSION_PRIO_TO_ASSIGN = {
		0, -- HOLD (consumes fuel HOLD_MISSION_MOVEMENT_COST fuel while moving)
		100, -- PATROL
		200, -- STRIKE FORCE
		200, -- CONVOY RAIDING
		200, -- CONVOY ESCORT
		200, -- MINES PLANTING
		100, -- MINES SWEEPING
		0, -- TRAIN
		0, -- RESERVE_FLEET
		100, -- NAVAL INVASION SUPPORT
	}

NDefines.NAI.HIGH_PRIO_NAVAL_MISSION_SCORES = {
		0, -- HOLD (consumes fuel HOLD_MISSION_MOVEMENT_COST fuel while moving)
		2000, -- PATROL
		1000, -- STRIKE FORCE
		1500, -- CONVOY RAIDING
		2000, -- CONVOY ESCORT
		-1, -- MINES PLANTING
		300, -- MINES SWEEPING
		0, -- TRAIN
		0, -- RESERVE_FLEET
		1000, -- NAVAL INVASION SUPPORT
	}

NDefines.NAI.SEA_PATH_LENGTH_SCORE_BASE = 0
NDefines.NAI.MAX_SCREEN_TASKFORCES_FOR_MINE_SWEEPING_PRIO_MAX_MINES = 200
NDefines.NAI.NAVY_PREFERED_MAX_SIZE = 80
NDefines.NAI.DOCKYARDS_PER_NAVAL_DESIRE_EFFECT = -50.0
NDefines.NAI.MIN_CAPITALS_FOR_CARRIER_TASKFORCE = 12
NDefines.NAI.CAPITALS_TO_CARRIER_RATIO = 3
NDefines.NAI.SCREENS_TO_CAPITAL_RATIO = 5.0
NDefines.NAI.SUB_TASKFORCE_MAX_SHIP_COUNT = 6
NDefines.NAI.SCREEN_TASKFORCE_MAX_SHIP_COUNT = 5
NDefines.NAI.MAX_PATROL_TO_STRIKE_FORCE_RATIO = 4.0
NDefines.NAI.REGION_THREAT_PER_SUNK_CONVOY = 25
NDefines.NAI.REGION_THREAT_LEVEL_TO_BLOCK_REGION = 25 * 400
NDefines.NAI.REGION_CONVOY_DANGER_DAILY_DECAY = 10
NDefines.NAI.MIN_INVASION_AREA_SIZE_FOR_FLOATING_HARBORS = 3
NDefines.NAI.AI_PREFERRED_TACTIC_WEEKLY_CHANGE_CHANCE = 0.00
NDefines.NAI.AREA_DEFENSE_CIVIL_WAR_IMPORTANCE = 5.0 --test
NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_LOW = 0.75 --test
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_LOW = 0.75 --test
NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_MED = 0.65 --test
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_MED = 0.65	 --test
NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_HIGH = 0.5 --test		
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_HIGH = 0.5 --test	
NDefines.NAI.DYNAMIC_STRATEGIES_THREAT_FACTOR = 8.0 --test
NDefines.NAI.AVERAGE_SUPPLY_USE_PESSIMISM = 2.0 --test
NDefines.NAITheatre.FRONT_EVAL_UNIT_SUPPLY_AND_ORG_LACK_IMPACT = 1.5 --test
NDefines.NAITheatre.AI_THEATRE_DISTRIBUTION_MAX_PERCENT_UNMET_DEMAND_PER_FRONT = 0.5 --test
NDefines.NAI.LAND_DEFENSE_SUPPLY_HUB_IMPORTANCE = 9
NDefines.NAI.ASSIGN_TANKS_TO_MOUNTAINS = -15
NDefines.NAI.ASSIGN_TANKS_TO_JUNGLE = -20
NDefines.NAI.RESERVE_TO_COMMITTED_BALANCE = 0.3
NDefines.NSupply.AI_FRONT_DIVISIONS_PER_SUPPLY_POINT = 0.85
NDefines.NAITheatre.AI_THEATRE_SUPPLY_CRISIS_LIMIT = 0.25
NDefines.NAI.PLAN_VALUE_TO_EXECUTE = -0.61
NDefines.NAI.FRONT_EVAL_UNIT_AIR_SUP_IMPACT = 2.0
NDefines.NAI.AI_FRONT_MOVEMENT_FACTOR_FOR_READY = 0.25
NDefines.NSupply.AI_FRONT_MINIMUM_UNITS_PER_PROVINCE_FOR_SUPPLY_CALCULATIONS = 0	-- Vanilla is 1
NDefines.NAI.PLAN_ACTIVATION_MAJOR_WEIGHT_FACTOR = 1.5
NDefines.NAI.PLAN_ACTIVATION_PLAYER_WEIGHT_FACTOR = 2
NDefines.NAI.PLAN_STEP_COST_LIMIT = 15
NDefines.NAI.PLAN_ATTACK_DEPTH_FACTOR = 0.5
NDefines.NAI.AREA_DEFENSE_BASE_IMPORTANCE = 30
NDefines.NAI.STATE_CONTROL_FOR_AREA_DEFENSE = 0.60
NDefines.NAI.MAX_SUPPLY_DIVISOR = 1.50
NDefines.NAI.FALLBACK_LOSING_FACTOR = 0.0
NDefines.NAI.DIVISION_SUPPLY_RATIO_TO_MOTORIZE = 1
NDefines.NAI.ENTRENCHMENT_WEIGHT = 4.0
NDefines.NAI.MIN_FIELD_STRENGTH_TO_BUILD_UNITS = 0.70
NDefines.NAI.ATTACK_HEAVILY_DEFENDED_LIMIT = 0.5
NDefines.NAI.MAX_MICRO_ATTACKS_PER_ORDER = 5
NDefines.NAI.MICRO_POCKET_SIZE = 3
NDefines.NAI.POCKET_DISTANCE_MAX = 6000
NDefines.NAI.FRONT_CUTOFF_MIN_EDGE_PROXIMITY = 1
NDefines.NAI.FRONT_BULGE_RATIO_LOWER_CUTOFF = 1.2
NDefines.NAI.FRONT_BULGE_RATIO_UPPER_CUTOFF = 1.8
NDefines.NAI.FRONT_EVAL_UNIT_ACCURACY = 1.5
NDefines.NAI.MIN_FORCE_RATIO_TO_PROTECT = 0
NDefines.NAI.FRONT_EVAL_PERCENT_TO_ASSIST_ALLY_FRONT = 0
NDefines.NAI.VP_LEVEL_IMPORTANCE_MEDIUM = 1
NDefines.NAI.VP_LEVEL_IMPORTANCE_LOW = 1 --keep high at 30
NDefines.NAI.PLAN_MIN_SIZE_FOR_FALLBACK = 2000
NDefines.NAI.MIN_PLAN_VALUE_TO_MICRO_INACTIVE = 0.15
NDefines.NAI.UNIT_ASSIGNMENT_TERRAIN_IMPORTANCE = 10.0
NDefines.NAI.FRONT_UNITS_CAP_FACTOR = 20.0
NDefines.NAI.RAIDS_CREATE_FREQUENCY_DAYS = 20
NDefines.NAI.RAIDS_COMMAND_POWER_CAP_TO_CREATE = 150.0 
NDefines.NAI.COMMAND_POWER_BEFORE_SPEND_ON_TRAITS = 10.0
NDefines.NAI.ARMY_LEADER_ASSIGN_NR_TRAITS = 0
NDefines.NAI.LOCATION_BALANCE_TO_ADVANCE = 0.00
NDefines.NAI.MAIN_ENEMY_FRONT_IMPORTANCE = 4.0
NDefines.NAI.MIN_NUM_CONQUERED_PROVINCES_TO_DEPRIO_NAVAL_INVADED_FRONTS = 100
NDefines.NAI.MAX_INVASION_SIZE = 24
NDefines.NAI.PLAN_FRONT_SECTION_MAX_LENGTH = 6 --test
NDefines.NAI.PLAN_FRONT_SECTION_MIN_LENGTH = 2 --test
NDefines.NAI.AIFC_CA_DIVISIONS_PER_PROVINCE = 2.5
NDefines.NAI.AIFC_ACTIVATE_AVG_ORG_RATIO_THRESHOLD = 0.4
NDefines.NAI.AIFC_ACTIVATE_IN_POSITION_RATIO_THRESHOLD = 0.3
NDefines.NAI.AIFC_TARGET_SUPPLY_HUB_BASE_SCORE = 30.0
NDefines.NAI.AIFC_TARGET_NAVAL_BASE_BASE_SCORE = 15.0
NDefines.NAI.AIFC_TARGET_NAVAL_BASE_SCORE_PER_LEVEL = 2.0
NDefines.NAI.AIFC_REFRESH_NEED_PER_DAY = 2.0
NDefines.NAI.AIFC_REFRESH_NEED_SUPPLY_FACTOR_PER_DAY = 1.10
NDefines.NAI.AIFC_PATH_COST_TRN_MOUNTAINS = 4.0
NDefines.NAI.AIFC_PATH_COST_TRN_MARSH = 3.0
NDefines.NAI.AIFC_PATH_COST_TRN_PLAINS = 1.5
NDefines.NAI.AIFC_PATH_COST_TRN_FOREST = 1.5
NDefines.NAI.AIFC_PATH_COST_TRN_URBAN = 0.50
NDefines.NAI.AIFC_PATH_COST_ADJ_RIVER = 1.5
NDefines.NAI.AIFC_PATH_COST_ADJ_RIVER_LARGE = 3.25
NDefines.NAI.AIFC_FRESHNESS_ADD_ON_PROGRESS = 22.0
NDefines.NAI.AIFC_PATH_COST_RAILWAY_CONNECTION = 0.80
NDefines.NAI.AIFC_PATH_COST_HAS_SUPPLY_HUB = 0.50
NDefines.NAI.AIFC_TARGET_SHORT_PATH_PENALTY_FACTOR = 0 --short path more ideal now?
NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_HARDNESS = 800.0
NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_EXPERIENCE = 500.0
NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_ARMOR = 80.0
NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_SOFT_ATTACK = 12.0
NDefines.NAI.AIFC_UNIT_OFFENSIVE_SCORE_FACTOR_HARD_ATTACK = 16.0
NDefines.NAI.AIFC_UNIT_NUDGE_FREQUENCY_DAYS = 10.0
NDefines.NAI.AIFC_UPDATE_FREQUENCY_DAYS = 4
NDefines.NAI.NAVAL_STRIKE_PLANES_PER_SHIP = 50
NDefines.NAI.NAVAL_STRIKE_PLANES_PER_SHIP_ESCORTING = 20
NDefines.NAI.NAVAL_PATROL_PLANES_PER_SHIP_ESCORTING = 20
NDefines.NAI.MAX_FUEL_CONSUMPTION_RATIO_FOR_AIR_TRAINING = 3.00
NDefines.NAI.WANTED_MAX_FUEL_BUFFER_IN_DAYS_FOR_AIR_MAX_CONSUMPTION  = 2
NDefines.NAI.LAND_COMBAT_FIGHTERS_PER_PLANE = 3.0
NDefines.NAI.LAND_COMBAT_FRIEND_ARMIES_AIR_IMPORTANCE = 2.0
NDefines.NAI.LAND_COMBAT_OUR_ARMIES_AIR_IMPORTANCE = 8.0
NDefines.NAI.LAND_COMBAT_FRIEND_COMBATS_AIR_IMPORTANCE = 5.0
NDefines.NAI.LAND_COMBAT_OUR_COMBATS_AIR_IMPORTANCE = 1000
NDefines.NAI.LAND_COMBAT_ENEMY_COASTAL_FORTS_AIR_IMPORTANCE = 20.0
NDefines.NAir.AIR_WING_FLIGHT_SPEED_MULT = 0.05
NDefines.NAI.AI_AIR_MISSION_COVERAGE_TO_STAY_PUT = 0.75
NDefines.NAI.AIR_SCORE_DISTANCE_IMPACT = 0.0
NDefines.NAI.DAYS_BETWEEN_AIR_PRIORITIES_UPDATE = 7
NDefines.NAI.LAND_DEFENSE_FIGHERS_PER_PLANE = 2.5